<?xml version="1.0" encoding="utf-8"?>
<xliff xmlns="urn:oasis:names:tc:xliff:document:1.2" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" version="1.2" xsi:schemaLocation="urn:oasis:names:tc:xliff:document:1.2 xliff-core-1.2-transitional.xsd">
  <file datatype="xml" original="NullReferenceException.xml" source-language="en-US" target-language="zh-CN">
    <header>
      <tool tool-id="mdxliff" tool-name="mdxliff" tool-version="1.0-15c36f0" tool-company="Microsoft" />
      <xliffext:skl_file_name xmlns:xliffext="urn:microsoft:content:schema:xliffextensions">02cd5861-7ce2-4a82-b358-31f8435a0ac5871adebd50877699047b62f9d350cf2555dfe480.skl</xliffext:skl_file_name>
      <xliffext:version xmlns:xliffext="urn:microsoft:content:schema:xliffextensions">1.2</xliffext:version>
      <xliffext:ms.openlocfilehash xmlns:xliffext="urn:microsoft:content:schema:xliffextensions">871adebd50877699047b62f9d350cf2555dfe480</xliffext:ms.openlocfilehash>
      <xliffext:ms.sourcegitcommit xmlns:xliffext="urn:microsoft:content:schema:xliffextensions">d31dc2ede16f6f7bc64e90d9f897ff54c4e3869b</xliffext:ms.sourcegitcommit>
      <xliffext:ms.lasthandoff xmlns:xliffext="urn:microsoft:content:schema:xliffextensions">04/03/2018</xliffext:ms.lasthandoff>
      <xliffext:moniker_ids xmlns:xliffext="urn:microsoft:content:schema:xliffextensions">netcore-1.0,netcore-1.1,netcore-2.0,netcore-2.1,netframework-4.5.1,netframework-4.5.2,netframework-4.5,netframework-4.6.1,netframework-4.6.2,netframework-4.6,netframework-4.7.1,netframework-4.7,netstandard-1.0,netstandard-1.1,netstandard-1.2,netstandard-1.3,netstandard-1.4,netstandard-1.5,netstandard-1.6,netstandard-2.0,xamarinandroid-7.1,xamarinios-10.8,xamarinmac-3.0</xliffext:moniker_ids>
    </header>
    <body>
      <group id="content" extype="content">
        <trans-unit id="101" translate="yes" xml:space="preserve" uid="T:System.NullReferenceException">
          <source>The exception that is thrown when there is an attempt to dereference a null object reference.</source>
          <target state="translated">尝试取消引用空对象引用时引发的异常。</target>       </trans-unit>
        <trans-unit id="102" translate="yes" xml:space="preserve" extradata="MT" uid="T:System.NullReferenceException">
          <source>A <ph id="ph1">&lt;xref:System.NullReferenceException&gt;</ph> exception is thrown when you try to access a member on a type whose value is <ph id="ph2">`null`</ph>.</source>
          <target state="translated">A<ph id="ph1">&lt;xref:System.NullReferenceException&gt;</ph>当你尝试访问其值的类型成员时引发异常<ph id="ph2">`null`</ph>。</target>       </trans-unit>
        <trans-unit id="103" translate="yes" xml:space="preserve" extradata="MT" uid="T:System.NullReferenceException">
          <source>A <ph id="ph1">&lt;xref:System.NullReferenceException&gt;</ph> exception typically reflects developer error and is thrown in the following scenarios:</source>
          <target state="translated">A<ph id="ph1">&lt;xref:System.NullReferenceException&gt;</ph>异常通常反映开发人员错误，并且在以下方案中引发：</target>       </trans-unit>
        <trans-unit id="104" translate="yes" xml:space="preserve" extradata="MT" uid="T:System.NullReferenceException">
          <source>You've forgotten to instantiate a reference type.</source>
          <target state="translated">你忘记了实例化一个引用类型。</target>       </trans-unit>
        <trans-unit id="105" translate="yes" xml:space="preserve" extradata="MT" uid="T:System.NullReferenceException">
          <source>In the following example, <ph id="ph1">`names`</ph> is declared but never instantiated:</source>
          <target state="translated">在下面的示例中，<ph id="ph1">`names`</ph>声明，但决不实例化：</target>       </trans-unit>
        <trans-unit id="106" translate="yes" xml:space="preserve" extradata="MT" uid="T:System.NullReferenceException">
          <source>Some compilers issue a warning when they compile this code.</source>
          <target state="translated">它们编译此代码时，一些编译器会发出警告。</target>       </trans-unit>
        <trans-unit id="107" translate="yes" xml:space="preserve" extradata="MT" uid="T:System.NullReferenceException">
          <source>Others issue an error, and the compilation fails.</source>
          <target state="translated">其他人发出错误，并且编译将失败。</target>       </trans-unit>
        <trans-unit id="108" translate="yes" xml:space="preserve" extradata="MT" uid="T:System.NullReferenceException">
          <source>To address this problem, instantiate the object so that its value is no longer <ph id="ph1">`null`</ph>.</source>
          <target state="translated">若要解决此问题，实例化对象，以便其值不再<ph id="ph1">`null`</ph>。</target>       </trans-unit>
        <trans-unit id="109" translate="yes" xml:space="preserve" extradata="MT" uid="T:System.NullReferenceException">
          <source>The following example does this by calling a type's class constructor.</source>
          <target state="translated">下面的示例将这是通过调用类型的类构造函数。</target>       </trans-unit>
        <trans-unit id="110" translate="yes" xml:space="preserve" extradata="MT" uid="T:System.NullReferenceException">
          <source>You've forgotten to dimension an array before initializing it.</source>
          <target state="translated">你忘记到在初始化之前维度数组。</target>       </trans-unit>
        <trans-unit id="111" translate="yes" xml:space="preserve" extradata="MT" uid="T:System.NullReferenceException">
          <source>In the following example, <ph id="ph1">`values`</ph> is declared to be an integer array, but the number of elements that it contains is never specified.</source>
          <target state="translated">在下面的示例中，<ph id="ph1">`values`</ph>被声明为一个整数数组，但永远不会指定它所包含的元素的数目。</target>       </trans-unit>
        <trans-unit id="112" translate="yes" xml:space="preserve" extradata="MT" uid="T:System.NullReferenceException">
          <source>The attempt to initialize its values therefore thrown a  <ph id="ph1">&lt;xref:System.NullReferenceException&gt;</ph> exception.</source>
          <target state="translated">尝试初始化因此引发其值<ph id="ph1">&lt;xref:System.NullReferenceException&gt;</ph>异常。</target>       </trans-unit>
        <trans-unit id="113" translate="yes" xml:space="preserve" extradata="MT" uid="T:System.NullReferenceException">
          <source>You can eliminate the exception by declaring the number of elements in the array before initializing it, as the following example does.</source>
          <target state="translated">通过在进行初始化之前声明的数组中的元素数，下面的示例一样，可以消除此异常。</target>       </trans-unit>
        <trans-unit id="114" translate="yes" xml:space="preserve" extradata="MT" uid="T:System.NullReferenceException">
          <source>For more information on declaring and initializing arrays, see <bpt id="p1">[</bpt>Arrays<ept id="p1">](http://msdn.microsoft.com/library/bb79bdde-e570-4c30-adb0-1dd5759ae041)</ept> and <bpt id="p2">[</bpt>Arrays<ept id="p2">](http://msdn.microsoft.com/library/dbf29737-b589-4443-bee6-a27588d9c67e)</ept>.</source>
          <target state="translated">声明和初始化数组的详细信息，请参阅<bpt id="p1">[</bpt>数组<ept id="p1">](http://msdn.microsoft.com/library/bb79bdde-e570-4c30-adb0-1dd5759ae041)</ept>和<bpt id="p2">[</bpt>数组<ept id="p2">](http://msdn.microsoft.com/library/dbf29737-b589-4443-bee6-a27588d9c67e)</ept>。</target>       </trans-unit>
        <trans-unit id="115" translate="yes" xml:space="preserve" extradata="MT" uid="T:System.NullReferenceException">
          <source>You get a <bpt id="p1">**</bpt>null<ept id="p1">**</ept> return value from a method, and then call a method on the returned type.</source>
          <target state="translated">你获取<bpt id="p1">**</bpt>null<ept id="p1">**</ept>从方法返回，返回值，然后在返回的类型上调用方法。</target>       </trans-unit>
        <trans-unit id="116" translate="yes" xml:space="preserve" extradata="MT" uid="T:System.NullReferenceException">
          <source>This sometimes is the result of a documentation error; the documentation fails to note that a method call can return <ph id="ph1">`null`</ph>.</source>
          <target state="translated">这有时是由错误引起的文档;文档将失败，需要注意的方法调用可以返回<ph id="ph1">`null`</ph>。</target>       </trans-unit>
        <trans-unit id="117" translate="yes" xml:space="preserve" extradata="MT" uid="T:System.NullReferenceException">
          <source>In other cases, your code erroneously assumes that the method will always return a non-<bpt id="p1">**</bpt>null<ept id="p1">**</ept> value.</source>
          <target state="translated">在其他情况下，你的代码错误地假定该方法将始终返回非<bpt id="p1">**</bpt>null<ept id="p1">**</ept>值。</target>       </trans-unit>
        <trans-unit id="118" translate="yes" xml:space="preserve" extradata="MT" uid="T:System.NullReferenceException">
          <source>The code in the following example assumes that the <ph id="ph1">&lt;xref:System.Array.Find%2A?displayProperty=nameWithType&gt;</ph> method always returns <ph id="ph2">`Person`</ph> object whose <ph id="ph3">`FirstName`</ph> field matches a search string.</source>
          <target state="translated">下面的示例中的代码假定<ph id="ph1">&lt;xref:System.Array.Find%2A?displayProperty=nameWithType&gt;</ph>方法始终返回<ph id="ph2">`Person`</ph>对象，其<ph id="ph3">`FirstName`</ph>字段匹配的搜索字符串。</target>       </trans-unit>
        <trans-unit id="119" translate="yes" xml:space="preserve" extradata="MT" uid="T:System.NullReferenceException">
          <source>Because there is no match, the runtime throws a <ph id="ph1">&lt;xref:System.NullReferenceException&gt;</ph> exception.</source>
          <target state="translated">由于没有任何匹配项，则运行时会引发<ph id="ph1">&lt;xref:System.NullReferenceException&gt;</ph>异常。</target>       </trans-unit>
        <trans-unit id="120" translate="yes" xml:space="preserve" extradata="MT" uid="T:System.NullReferenceException">
          <source>To address this problem, test the method's return value to ensure that it is not <ph id="ph1">`null`</ph> before calling any of its members, as the following example does.</source>
          <target state="translated">若要解决此问题，测试方法的返回值，以确保它不是<ph id="ph1">`null`</ph>之前调用任何的成员，如以下示例执行。</target>       </trans-unit>
        <trans-unit id="121" translate="yes" xml:space="preserve" extradata="MT" uid="T:System.NullReferenceException">
          <source>You're using an expression (for example, you're chaining a list of methods or properties together) to retrieve a value and, although you're checking whether the value is <ph id="ph1">`null`</ph>, the runtime still throws a <ph id="ph2">&lt;xref:System.NullReferenceException&gt;</ph> exception.</source>
          <target state="translated">要使用表达式 （例如，要链接的方法或属性列表在一起） 来检索一个值，尽管你要检查的值是否<ph id="ph1">`null`</ph>，运行时仍会引发<ph id="ph2">&lt;xref:System.NullReferenceException&gt;</ph>异常。</target>       </trans-unit>
        <trans-unit id="122" translate="yes" xml:space="preserve" extradata="MT" uid="T:System.NullReferenceException">
          <source>This occurs because one of the intermediate values in the expression returns <ph id="ph1">`null`</ph>.</source>
          <target state="translated">发生这种情况是因为其中一个表达式中的中间值返回<ph id="ph1">`null`</ph>。</target>       </trans-unit>
        <trans-unit id="123" translate="yes" xml:space="preserve" extradata="MT" uid="T:System.NullReferenceException">
          <source>As a result, your rest for <ph id="ph1">`null`</ph> is never evaluated.</source>
          <target state="translated">因此，你其余部分<ph id="ph1">`null`</ph>从不进行计算。</target>       </trans-unit>
        <trans-unit id="124" translate="yes" xml:space="preserve" extradata="MT" uid="T:System.NullReferenceException">
          <source>The following example defines a <ph id="ph1">`Pages`</ph> object that  caches information about web pages, which are presented by <ph id="ph2">`Page`</ph> objects.</source>
          <target state="translated">下面的示例定义<ph id="ph1">`Pages`</ph>缓存 web 页，它们提供的有关信息的对象<ph id="ph2">`Page`</ph>对象。</target>       </trans-unit>
        <trans-unit id="125" translate="yes" xml:space="preserve" extradata="MT" uid="T:System.NullReferenceException">
          <source>The <ph id="ph1">`Example.Main`</ph> method checks whether the current web page has a non-null title and, if it does, displays the title.</source>
          <target state="translated"><ph id="ph1">`Example.Main`</ph>方法检查是否当前的 web 页具有非 null 标题，如果是这样，显示的标题。</target>       </trans-unit>
        <trans-unit id="126" translate="yes" xml:space="preserve" extradata="MT" uid="T:System.NullReferenceException">
          <source>Despite this check, however, the method throws a <ph id="ph1">&lt;xref:System.NullReferenceException&gt;</ph> exception.</source>
          <target state="translated">尽管此检查，但是，该方法将引发<ph id="ph1">&lt;xref:System.NullReferenceException&gt;</ph>异常。</target>       </trans-unit>
        <trans-unit id="127" translate="yes" xml:space="preserve" extradata="MT" uid="T:System.NullReferenceException">
          <source>The exception is thrown because <ph id="ph1">`pages.CurrentPage`</ph> returns <ph id="ph2">`null`</ph> if no page information is  stored in the cache.</source>
          <target state="translated">引发异常，因为<ph id="ph1">`pages.CurrentPage`</ph>返回<ph id="ph2">`null`</ph>如果没有页信息存储在缓存中。</target>       </trans-unit>
        <trans-unit id="128" translate="yes" xml:space="preserve" extradata="MT" uid="T:System.NullReferenceException">
          <source>This exception can be corrected by testing the value of the <ph id="ph1">`CurrentPage`</ph> property before retrieving the current <ph id="ph2">`Page`</ph> object's <ph id="ph3">`Title`</ph> property, as the following example does:</source>
          <target state="translated">可以通过测试的值来解决此异常<ph id="ph1">`CurrentPage`</ph>之前检索当前的属性<ph id="ph2">`Page`</ph>对象的<ph id="ph3">`Title`</ph>属性，如下面的示例未：</target>       </trans-unit>
        <trans-unit id="129" translate="yes" xml:space="preserve" extradata="MT" uid="T:System.NullReferenceException">
          <source>You're enumerating the elements of an array that contains reference types, and your attempt to process one of the elements throws a <ph id="ph1">&lt;xref:System.NullReferenceException&gt;</ph> exception.</source>
          <target state="translated">要枚举的一个数组，包含引用类型，以及到进程的元素的一个引发你尝试元素<ph id="ph1">&lt;xref:System.NullReferenceException&gt;</ph>异常。</target>       </trans-unit>
        <trans-unit id="130" translate="yes" xml:space="preserve" extradata="MT" uid="T:System.NullReferenceException">
          <source>The following example defines a string array.</source>
          <target state="translated">下面的示例定义的字符串数组。</target>       </trans-unit>
        <trans-unit id="131" translate="yes" xml:space="preserve" extradata="MT" uid="T:System.NullReferenceException">
          <source>A <ph id="ph1">`for`</ph> statement enumerates the elements in the array and calls each string's <ph id="ph2">&lt;xref:System.String.Trim%2A&gt;</ph> method before displaying the string.</source>
          <target state="translated">A<ph id="ph1">`for`</ph>语句枚举数组中的元素，并调用每个字符串<ph id="ph2">&lt;xref:System.String.Trim%2A&gt;</ph>方法，然后才能显示字符串。</target>       </trans-unit>
        <trans-unit id="132" translate="yes" xml:space="preserve" extradata="MT" uid="T:System.NullReferenceException">
          <source>This exception occurs if you assume that each element of the array must contain a non-null value, and the value of the array element is in fact <ph id="ph1">`null`</ph>.</source>
          <target state="translated">如果你假定数组的每个元素必须包含非 null 值，而数组元素的值中的事实是，则会发生此异常<ph id="ph1">`null`</ph>。</target>       </trans-unit>
        <trans-unit id="133" translate="yes" xml:space="preserve" extradata="MT" uid="T:System.NullReferenceException">
          <source>The exception can be eliminated by testing whether the element is <ph id="ph1">`null`</ph> before performing any operation on that element, as the following example shows.</source>
          <target state="translated">元素是否是，可以进行测试，以消除异常<ph id="ph1">`null`</ph>然后再执行针对该元素的任何操作，如下面的示例所示。</target>       </trans-unit>
        <trans-unit id="134" translate="yes" xml:space="preserve" extradata="MT" uid="T:System.NullReferenceException">
          <source>A <ph id="ph1">&lt;xref:System.NullReferenceException&gt;</ph> exception is thrown by a method that is passed <ph id="ph2">`null`</ph>.</source>
          <target state="translated">A<ph id="ph1">&lt;xref:System.NullReferenceException&gt;</ph>传递的方法引发异常<ph id="ph2">`null`</ph>。</target>       </trans-unit>
        <trans-unit id="135" translate="yes" xml:space="preserve" extradata="MT" uid="T:System.NullReferenceException">
          <source>Some methods validate the arguments that are passed to them.</source>
          <target state="translated">某些方法验证传递给它们的自变量。</target>       </trans-unit>
        <trans-unit id="136" translate="yes" xml:space="preserve" extradata="MT" uid="T:System.NullReferenceException">
          <source>If they do and one of the arguments is <ph id="ph1">`null`</ph>, the method throws an <ph id="ph2">&lt;xref:System.ArgumentNullException?displayProperty=nameWithType&gt;</ph> exception.</source>
          <target state="translated">如果它们，并且其中一个自变量是<ph id="ph1">`null`</ph>，该方法将引发<ph id="ph2">&lt;xref:System.ArgumentNullException?displayProperty=nameWithType&gt;</ph>异常。</target>       </trans-unit>
        <trans-unit id="137" translate="yes" xml:space="preserve" extradata="MT" uid="T:System.NullReferenceException">
          <source>Otherwise, it throws a <ph id="ph1">&lt;xref:System.NullReferenceException&gt;</ph> exception.</source>
          <target state="translated">否则，它会引发<ph id="ph1">&lt;xref:System.NullReferenceException&gt;</ph>异常。</target>       </trans-unit>
        <trans-unit id="138" translate="yes" xml:space="preserve" extradata="MT" uid="T:System.NullReferenceException">
          <source>The following example illustrates this scenario.</source>
          <target state="translated">下面的示例阐释了这种情况。</target>       </trans-unit>
        <trans-unit id="139" translate="yes" xml:space="preserve" extradata="MT" uid="T:System.NullReferenceException">
          <source>To address this issue, make sure that the argument passed to the method is not <ph id="ph1">`null`</ph>, or handle the thrown exception in a <ph id="ph2">`try…catch…finally`</ph> block.</source>
          <target state="translated">若要解决此问题，请确保传递给方法的参数不是<ph id="ph1">`null`</ph>，或处理中引发的异常<ph id="ph2">`try…catch…finally`</ph>块。</target>       </trans-unit>
        <trans-unit id="140" translate="yes" xml:space="preserve" extradata="MT" uid="T:System.NullReferenceException">
          <source>For more information, see <bpt id="p1">[</bpt>Exceptions<ept id="p1">](http://msdn.microsoft.com/library/f99a1d29-a2a8-47af-9707-9909f9010735)</ept>.</source>
          <target state="translated">有关详细信息，请参阅<bpt id="p1">[</bpt>异常<ept id="p1">](http://msdn.microsoft.com/library/f99a1d29-a2a8-47af-9707-9909f9010735)</ept>。</target>       </trans-unit>
        <trans-unit id="141" translate="yes" xml:space="preserve" extradata="MT" uid="T:System.NullReferenceException">
          <source>The following Microsoft intermediate language (MSIL) instructions throw <ph id="ph1">&lt;xref:System.NullReferenceException&gt;</ph>: <ph id="ph2">`callvirt`</ph>, <ph id="ph3">`cpblk`</ph>, <ph id="ph4">`cpobj`</ph>, <ph id="ph5">`initblk`</ph>, <ph id="ph6">`ldelem.&lt;type&gt;`</ph>, <ph id="ph7">`ldelema`</ph>, <ph id="ph8">`ldfld`</ph>, <ph id="ph9">`ldflda`</ph>, <ph id="ph10">`ldind.&lt;type&gt;`</ph>, <ph id="ph11">`ldlen`</ph>, <ph id="ph12">`stelem.&lt;type&gt;`</ph>, <ph id="ph13">`stfld`</ph>, <ph id="ph14">`stind.&lt;type&gt;`</ph>, <ph id="ph15">`throw`</ph>, and <ph id="ph16">`unbox`</ph>.</source>
          <target state="translated">以下 Microsoft 中间语言 (MSIL) 指令引发<ph id="ph1">&lt;xref:System.NullReferenceException&gt;</ph>: <ph id="ph2">`callvirt`</ph>， <ph id="ph3">`cpblk`</ph>， <ph id="ph4">`cpobj`</ph>， <ph id="ph5">`initblk`</ph>， <ph id="ph6">`ldelem.&lt;type&gt;`</ph>， <ph id="ph7">`ldelema`</ph>， <ph id="ph8">`ldfld`</ph>， <ph id="ph9">`ldflda`</ph>， <ph id="ph10">`ldind.&lt;type&gt;`</ph><ph id="ph11">`ldlen`</ph>， <ph id="ph12">`stelem.&lt;type&gt;`</ph>， <ph id="ph13">`stfld`</ph>， <ph id="ph14">`stind.&lt;type&gt;`</ph>， <ph id="ph15">`throw`</ph>，和<ph id="ph16">`unbox`</ph>。</target>       </trans-unit>
        <trans-unit id="142" translate="yes" xml:space="preserve" extradata="MT" uid="T:System.NullReferenceException">
          <source><ph id="ph1">&lt;xref:System.NullReferenceException&gt;</ph> uses the HRESULT COR_E_NULLREFERENCE, which has the value 0x80004003.</source>
          <target state="translated"><ph id="ph1">&lt;xref:System.NullReferenceException&gt;</ph> 使用 HRESULT COR_E_NULLREFERENCE，其值 0x80004003。</target>       </trans-unit>
        <trans-unit id="143" translate="yes" xml:space="preserve" extradata="MT" uid="T:System.NullReferenceException">
          <source>For a list of initial property values for an instance of <ph id="ph1">&lt;xref:System.NullReferenceException&gt;</ph>, see the <ph id="ph2">&lt;xref:System.NullReferenceException.%23ctor%2A&gt;</ph> constructors.</source>
          <target state="translated">有关的实例的初始属性值的列表<ph id="ph1">&lt;xref:System.NullReferenceException&gt;</ph>，请参阅<ph id="ph2">&lt;xref:System.NullReferenceException.%23ctor%2A&gt;</ph>构造函数。</target>       </trans-unit>
        <trans-unit id="144" translate="yes" xml:space="preserve" extradata="MT" uid="T:System.NullReferenceException">
          <source><bpt id="p1">**</bpt>Handling NullReferenceException in release code<ept id="p1">**</ept></source>
          <target state="translated"><bpt id="p1">**</bpt>处理发行代码中的 NullReferenceException<ept id="p1">**</ept></target>       </trans-unit>
        <trans-unit id="145" translate="yes" xml:space="preserve" extradata="MT" uid="T:System.NullReferenceException">
          <source>It's usually better to avoid a NullReferenceException than to handle it after it occurs.</source>
          <target state="translated">通常，最好避免 NullReferenceException 比处理后发生。</target>       </trans-unit>
        <trans-unit id="146" translate="yes" xml:space="preserve" extradata="MT" uid="T:System.NullReferenceException">
          <source>Handling an exception can make your code harder to maintain and understand, and can sometimes introduce other bugs.</source>
          <target state="translated">处理异常会导致代码更难维护和理解，并且有时会引入其他 bug。</target>       </trans-unit>
        <trans-unit id="147" translate="yes" xml:space="preserve" extradata="MT" uid="T:System.NullReferenceException">
          <source>A NullReferenceException is often a non-recoverable error.</source>
          <target state="translated">NullReferenceException 通常为不可恢复的错误。</target>       </trans-unit>
        <trans-unit id="148" translate="yes" xml:space="preserve" extradata="MT" uid="T:System.NullReferenceException">
          <source>In these cases, letting the exception stop the app might be the best alternative.</source>
          <target state="translated">在这些情况下，让异常停止应用可能是最佳替代方法。</target>       </trans-unit>
        <trans-unit id="149" translate="yes" xml:space="preserve" extradata="MT" uid="T:System.NullReferenceException">
          <source>However, there are many situations where handling the error can be useful:</source>
          <target state="translated">然而，在许多情况下，处理错误可能非常有用：</target>       </trans-unit>
        <trans-unit id="150" translate="yes" xml:space="preserve" extradata="MT" uid="T:System.NullReferenceException">
          <source>Your app can ignore objects that are null.</source>
          <target state="translated">你的应用可以忽略为 null 的对象。</target>       </trans-unit>
        <trans-unit id="151" translate="yes" xml:space="preserve" extradata="MT" uid="T:System.NullReferenceException">
          <source>For example, if your app retrieves and processes records in a database, you might be able to ignore some number of bad records that result in null objects.</source>
          <target state="translated">例如，如果你的应用检索并处理数据库中的记录，则你可以忽略一些导致 null 对象的错误记录。</target>       </trans-unit>
        <trans-unit id="152" translate="yes" xml:space="preserve" extradata="MT" uid="T:System.NullReferenceException">
          <source>Recording the bad data in a log file or in the application UI might be all you have to do.</source>
          <target state="translated">你可能仅需在日志文件或应用程序 UI 中记录错误数据。</target>       </trans-unit>
        <trans-unit id="153" translate="yes" xml:space="preserve" extradata="MT" uid="T:System.NullReferenceException">
          <source>You can recover from the exception.</source>
          <target state="translated">可以从异常中恢复。</target>       </trans-unit>
        <trans-unit id="154" translate="yes" xml:space="preserve" extradata="MT" uid="T:System.NullReferenceException">
          <source>For example, a call to a web service that returns a reference type might return null if the connection is lost or the connection times out. You can attempt to reestablish the connection and try the call again.</source>
          <target state="translated">例如，在连接丢失或连接超时的情况下，对返回引用类型的 Web 服务的调用可能会返回 null。可尝试重新建立连接并再次尝试调用。</target>       </trans-unit>
        <trans-unit id="155" translate="yes" xml:space="preserve" extradata="MT" uid="T:System.NullReferenceException">
          <source>You can restore the state of your app to a valid state.</source>
          <target state="translated">可将你的应用状态还原到有效状态。</target>       </trans-unit>
        <trans-unit id="156" translate="yes" xml:space="preserve" extradata="MT" uid="T:System.NullReferenceException">
          <source>For example, you might be performing a multi-step task that requires you to save information to a data store before you call a method that throws a NullReferenceException.</source>
          <target state="translated">例如，你可能要执行多步骤的任务，该任务需要你在调用引发 NullReferenceException 的方法之前将信息保存到数据存储。</target>       </trans-unit>
        <trans-unit id="157" translate="yes" xml:space="preserve" extradata="MT" uid="T:System.NullReferenceException">
          <source>If the uninitialized object would corrupt the data record, you can remove the previous data before you close the app.</source>
          <target state="translated">如果未初始化的对象可能会损坏数据记录，你可以在关闭应用之前删除之前的数据。</target>       </trans-unit>
        <trans-unit id="158" translate="yes" xml:space="preserve" extradata="MT" uid="T:System.NullReferenceException">
          <source>You want to report the exception.</source>
          <target state="translated">你需要报告异常。</target>       </trans-unit>
        <trans-unit id="159" translate="yes" xml:space="preserve" extradata="MT" uid="T:System.NullReferenceException">
          <source>For example, if the error was caused by a mistake from the user of your app, you can generate a message to help him supply the correct information.</source>
          <target state="translated">例如，如果该错误由应用用户的某个错误引起，你可以生成一条可帮助该用户提供正确信息的消息。</target>       </trans-unit>
        <trans-unit id="160" translate="yes" xml:space="preserve" extradata="MT" uid="T:System.NullReferenceException">
          <source>You can also log information about the error to help you fix the problem.</source>
          <target state="translated">你还可以记录有关该错误的信息来帮助你解决此问题。</target>       </trans-unit>
        <trans-unit id="161" translate="yes" xml:space="preserve" extradata="MT" uid="T:System.NullReferenceException">
          <source>Some frameworks, like ASP.NET, have a high-level exception handler that captures all errors to that the app never crashes; in that case, logging the exception might be the only way you can know that it occurs.</source>
          <target state="translated">某些框架（如 ASP.NET）具有高级别的异常处理程序，该处理程序可捕获所有错误，以便应用永远不会发生崩溃，在这种情况下，记录异常可能是你用来了解是否发生异常的唯一方式。</target>       </trans-unit>
        <trans-unit id="162" translate="yes" xml:space="preserve" uid="T:System.NullReferenceException">
          <source>Initializes a new instance of the <ph id="ph1">&lt;see cref="T:System.NullReferenceException" /&gt;</ph> class.</source>
          <target state="translated">初始化 <ph id="ph1">&lt;see cref="T:System.NullReferenceException" /&gt;</ph> 类的新实例。</target>       </trans-unit>
        <trans-unit id="163" translate="yes" xml:space="preserve" uid="M:System.NullReferenceException.#ctor">
          <source>Initializes a new instance of the <ph id="ph1">&lt;see cref="T:System.NullReferenceException" /&gt;</ph> class, setting the <ph id="ph2">&lt;see cref="P:System.Exception.Message" /&gt;</ph> property of the new instance to a system-supplied message that describes the error, such as "The value 'null' was found where an instance of an object was required."</source>
          <target state="translated">初始化 <ph id="ph1">&lt;see cref="T:System.NullReferenceException" /&gt;</ph> 类的新实例，将新实例的 <ph id="ph2">&lt;see cref="P:System.Exception.Message" /&gt;</ph> 属性设置为系统提供的描述错误的消息，如“在需要对象实例的地方找到了值‘null’。”。</target>       </trans-unit>
        <trans-unit id="164" translate="yes" xml:space="preserve" uid="M:System.NullReferenceException.#ctor">
          <source>This message takes into account the current system culture.</source>
          <target state="translated">此消息将当前系统区域性考虑在内。</target>       </trans-unit>
        <trans-unit id="165" translate="yes" xml:space="preserve" extradata="MT" uid="M:System.NullReferenceException.#ctor">
          <source>The following table shows the initial property values for an instance of <ph id="ph1">&lt;xref:System.NullReferenceException&gt;</ph>.</source>
          <target state="translated">下表显示 <ph id="ph1">&lt;xref:System.NullReferenceException&gt;</ph> 的实例的初始属性值。</target>       </trans-unit>
        <trans-unit id="166" translate="yes" xml:space="preserve" extradata="MT" uid="M:System.NullReferenceException.#ctor">
          <source>Property</source>
          <target state="translated">Property</target>       </trans-unit>
        <trans-unit id="167" translate="yes" xml:space="preserve" extradata="MT" uid="M:System.NullReferenceException.#ctor">
          <source>Value</source>
          <target state="translated">“值”</target>       </trans-unit>
        <trans-unit id="168" translate="yes" xml:space="preserve" extradata="MT" uid="M:System.NullReferenceException.#ctor">
          <source><ph id="ph1">`null`</ph>.</source>
          <target state="translated"><ph id="ph1">`null`</ph>。</target>       </trans-unit>
        <trans-unit id="169" translate="yes" xml:space="preserve" extradata="MT" uid="M:System.NullReferenceException.#ctor">
          <source>The localized error message string.</source>
          <target state="translated">本地化的错误消息字符串。</target>       </trans-unit>
        <trans-unit id="170" translate="yes" xml:space="preserve" uid="M:System.NullReferenceException.#ctor(System.String)">
          <source>A <ph id="ph1">&lt;see cref="T:System.String" /&gt;</ph> that describes the error.</source>
          <target state="translated">描述该错误的 <ph id="ph1">&lt;see cref="T:System.String" /&gt;</ph>。</target>       </trans-unit>
        <trans-unit id="171" translate="yes" xml:space="preserve" uid="M:System.NullReferenceException.#ctor(System.String)">
          <source>The content of <bpt id="p1">&lt;c&gt;</bpt>message<ept id="p1">&lt;/c&gt;</ept> is intended to be understood by humans.</source>
          <target state="translated">消息的内容被设计为人可理解的形式<bpt id="p1">&lt;c&gt;</bpt><ept id="p1">&lt;/c&gt;</ept>。</target>       </trans-unit>
        <trans-unit id="172" translate="yes" xml:space="preserve" uid="M:System.NullReferenceException.#ctor(System.String)">
          <source>The caller of this constructor is required to ensure that this string has been localized for the current system culture.</source>
          <target state="translated">此构造函数的调用方需要确保此字符串已针对当前系统区域性进行了本地化。</target>       </trans-unit>
        <trans-unit id="173" translate="yes" xml:space="preserve" uid="M:System.NullReferenceException.#ctor(System.String)">
          <source>Initializes a new instance of the <ph id="ph1">&lt;see cref="T:System.NullReferenceException" /&gt;</ph> class with a specified error message.</source>
          <target state="translated">用指定的错误消息初始化 <ph id="ph1">&lt;see cref="T:System.NullReferenceException" /&gt;</ph> 类的新实例。</target>       </trans-unit>
        <trans-unit id="174" translate="yes" xml:space="preserve" extradata="MT" uid="M:System.NullReferenceException.#ctor(System.String)">
          <source>The following table shows the initial property values for an instance of <ph id="ph1">&lt;xref:System.NullReferenceException&gt;</ph>.</source>
          <target state="translated">下表显示 <ph id="ph1">&lt;xref:System.NullReferenceException&gt;</ph> 的实例的初始属性值。</target>       </trans-unit>
        <trans-unit id="175" translate="yes" xml:space="preserve" extradata="MT" uid="M:System.NullReferenceException.#ctor(System.String)">
          <source>Property</source>
          <target state="translated">Property</target>       </trans-unit>
        <trans-unit id="176" translate="yes" xml:space="preserve" extradata="MT" uid="M:System.NullReferenceException.#ctor(System.String)">
          <source>Value</source>
          <target state="translated">“值”</target>       </trans-unit>
        <trans-unit id="177" translate="yes" xml:space="preserve" extradata="MT" uid="M:System.NullReferenceException.#ctor(System.String)">
          <source><ph id="ph1">`null`</ph>.</source>
          <target state="translated"><ph id="ph1">`null`</ph>。</target>       </trans-unit>
        <trans-unit id="178" translate="yes" xml:space="preserve" extradata="MT" uid="M:System.NullReferenceException.#ctor(System.String)">
          <source>The error message string.</source>
          <target state="translated">错误消息字符串。</target>       </trans-unit>
        <trans-unit id="179" translate="yes" xml:space="preserve" uid="M:System.NullReferenceException.#ctor(System.Runtime.Serialization.SerializationInfo,System.Runtime.Serialization.StreamingContext)">
          <source>The object that holds the serialized object data.</source>
          <target state="translated">承载序列化对象数据的对象。</target>       </trans-unit>
        <trans-unit id="180" translate="yes" xml:space="preserve" uid="M:System.NullReferenceException.#ctor(System.Runtime.Serialization.SerializationInfo,System.Runtime.Serialization.StreamingContext)">
          <source>The contextual information about the source or destination.</source>
          <target state="translated">关于来源和目标的上下文信息</target>       </trans-unit>
        <trans-unit id="181" translate="yes" xml:space="preserve" uid="M:System.NullReferenceException.#ctor(System.Runtime.Serialization.SerializationInfo,System.Runtime.Serialization.StreamingContext)">
          <source>Initializes a new instance of the <ph id="ph1">&lt;see cref="T:System.NullReferenceException" /&gt;</ph> class with serialized data.</source>
          <target state="translated">用序列化数据初始化 <ph id="ph1">&lt;see cref="T:System.NullReferenceException" /&gt;</ph> 类的新实例。</target>       </trans-unit>
        <trans-unit id="182" translate="yes" xml:space="preserve" extradata="MT" uid="M:System.NullReferenceException.#ctor(System.Runtime.Serialization.SerializationInfo,System.Runtime.Serialization.StreamingContext)">
          <source>This constructor is called during deserialization to reconstitute the exception object transmitted over a stream.</source>
          <target state="translated">此构造函数在反序列化过程中调用，以便重建通过流传输的异常对象。</target>       </trans-unit>
        <trans-unit id="183" translate="yes" xml:space="preserve" extradata="MT" uid="M:System.NullReferenceException.#ctor(System.Runtime.Serialization.SerializationInfo,System.Runtime.Serialization.StreamingContext)">
          <source>For more information, see <bpt id="p1">[</bpt>XML and SOAP Serialization<ept id="p1">](~/docs/standard/serialization/xml-and-soap-serialization.md)</ept>.</source>
          <target state="translated">有关详细信息，请参阅<bpt id="p1">[</bpt>XML 和 SOAP 序列化<ept id="p1">](~/docs/standard/serialization/xml-and-soap-serialization.md)</ept>。</target>       </trans-unit>
        <trans-unit id="184" translate="yes" xml:space="preserve" uid="M:System.NullReferenceException.#ctor(System.String,System.Exception)">
          <source>The error message that explains the reason for the exception.</source>
          <target state="translated">解释异常原因的错误消息。</target>       </trans-unit>
        <trans-unit id="185" translate="yes" xml:space="preserve" uid="M:System.NullReferenceException.#ctor(System.String,System.Exception)">
          <source>The exception that is the cause of the current exception.</source>
          <target state="translated">导致当前异常的异常。</target>       </trans-unit>
        <trans-unit id="186" translate="yes" xml:space="preserve" uid="M:System.NullReferenceException.#ctor(System.String,System.Exception)">
          <source>If the <bpt id="p1">&lt;c&gt;</bpt>innerException<ept id="p1">&lt;/c&gt;</ept> parameter is not <ph id="ph1">&lt;see langword="null" /&gt;</ph>, the current exception is raised in a <ph id="ph2">&lt;see langword="catch" /&gt;</ph> block that handles the inner exception.</source>
          <target state="translated">如果 <bpt id="p1">&lt;c&gt;</bpt>innerException<ept id="p1">&lt;/c&gt;</ept> 参数不为 <ph id="ph1">&lt;see langword="null" /&gt;</ph>，则当前异常会在处理内部异常的 <ph id="ph2">&lt;see langword="catch" /&gt;</ph> 块中引发。</target>       </trans-unit>
        <trans-unit id="187" translate="yes" xml:space="preserve" uid="M:System.NullReferenceException.#ctor(System.String,System.Exception)">
          <source>Initializes a new instance of the <ph id="ph1">&lt;see cref="T:System.NullReferenceException" /&gt;</ph> class with a specified error message and a reference to the inner exception that is the cause of this exception.</source>
          <target state="translated">使用指定的错误消息和对作为此异常原因的内部异常的引用来初始化 <ph id="ph1">&lt;see cref="T:System.NullReferenceException" /&gt;</ph> 类的新实例。</target>       </trans-unit>
        <trans-unit id="188" translate="yes" xml:space="preserve" extradata="MT" uid="M:System.NullReferenceException.#ctor(System.String,System.Exception)">
          <source>An exception that is thrown as a direct result of a previous exception should include a reference to the previous exception in the <ph id="ph1">&lt;xref:System.Exception.InnerException%2A&gt;</ph> property.</source>
          <target state="translated">因前一个异常而直接引发的异常应在 <ph id="ph1">&lt;xref:System.Exception.InnerException%2A&gt;</ph> 属性中包含对前一个异常的引用。</target>       </trans-unit>
        <trans-unit id="189" translate="yes" xml:space="preserve" extradata="MT" uid="M:System.NullReferenceException.#ctor(System.String,System.Exception)">
          <source>The <ph id="ph1">&lt;xref:System.Exception.InnerException%2A&gt;</ph> property returns the same value that is passed into the constructor, or <ph id="ph2">`null`</ph> if the <ph id="ph3">&lt;xref:System.Exception.InnerException%2A&gt;</ph> property does not supply the inner exception value to the constructor.</source>
          <target state="translated"><ph id="ph1">&lt;xref:System.Exception.InnerException%2A&gt;</ph> 属性返回的值与传递到构造函数中的值相同；或者，如果 <ph id="ph2">`null`</ph> 属性没有向构造函数提供内部异常值，则为 <ph id="ph3">&lt;xref:System.Exception.InnerException%2A&gt;</ph>。</target>       </trans-unit>
        <trans-unit id="190" translate="yes" xml:space="preserve" extradata="MT" uid="M:System.NullReferenceException.#ctor(System.String,System.Exception)">
          <source>The following table shows the initial property values for an instance of <ph id="ph1">&lt;xref:System.NullReferenceException&gt;</ph>.</source>
          <target state="translated">下表显示 <ph id="ph1">&lt;xref:System.NullReferenceException&gt;</ph> 的实例的初始属性值。</target>       </trans-unit>
        <trans-unit id="191" translate="yes" xml:space="preserve" extradata="MT" uid="M:System.NullReferenceException.#ctor(System.String,System.Exception)">
          <source>Property</source>
          <target state="translated">Property</target>       </trans-unit>
        <trans-unit id="192" translate="yes" xml:space="preserve" extradata="MT" uid="M:System.NullReferenceException.#ctor(System.String,System.Exception)">
          <source>Value</source>
          <target state="translated">“值”</target>       </trans-unit>
        <trans-unit id="193" translate="yes" xml:space="preserve" extradata="MT" uid="M:System.NullReferenceException.#ctor(System.String,System.Exception)">
          <source>The inner exception reference.</source>
          <target state="translated">内部异常引用。</target>       </trans-unit>
        <trans-unit id="194" translate="yes" xml:space="preserve" extradata="MT" uid="M:System.NullReferenceException.#ctor(System.String,System.Exception)">
          <source>The error message string.</source>
          <target state="translated">错误消息字符串。</target>       </trans-unit>
      </group>
    </body>
  </file>
</xliff>