<?xml version="1.0" encoding="utf-8"?>
<xliff xmlns="urn:oasis:names:tc:xliff:document:1.2" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" version="1.2" xsi:schemaLocation="urn:oasis:names:tc:xliff:document:1.2 xliff-core-1.2-transitional.xsd">
  <file datatype="xml" original="XamlInternalException.xml" source-language="en-US" target-language="zh-CN">
    <header>
      <tool tool-id="mdxliff" tool-name="mdxliff" tool-version="1.0-15c36f0" tool-company="Microsoft" />
      <xliffext:skl_file_name xmlns:xliffext="urn:microsoft:content:schema:xliffextensions">02cd5861-7ce2-4a82-b358-31f8435a0ac50729fa9645baf6a20d37770d139f103712c6612f.skl</xliffext:skl_file_name>
      <xliffext:version xmlns:xliffext="urn:microsoft:content:schema:xliffextensions">1.2</xliffext:version>
      <xliffext:ms.openlocfilehash xmlns:xliffext="urn:microsoft:content:schema:xliffextensions">0729fa9645baf6a20d37770d139f103712c6612f</xliffext:ms.openlocfilehash>
      <xliffext:ms.sourcegitcommit xmlns:xliffext="urn:microsoft:content:schema:xliffextensions">d31dc2ede16f6f7bc64e90d9f897ff54c4e3869b</xliffext:ms.sourcegitcommit>
      <xliffext:ms.lasthandoff xmlns:xliffext="urn:microsoft:content:schema:xliffextensions">04/03/2018</xliffext:ms.lasthandoff>
      <xliffext:moniker_ids xmlns:xliffext="urn:microsoft:content:schema:xliffextensions">netframework-4.5.1,netframework-4.5.2,netframework-4.5,netframework-4.6.1,netframework-4.6.2,netframework-4.6,netframework-4.7.1,netframework-4.7</xliffext:moniker_ids>
    </header>
    <body>
      <group id="content" extype="content">
        <trans-unit id="101" translate="yes" xml:space="preserve" uid="T:System.Xaml.XamlInternalException">
          <source>The exception that is thrown for internal inconsistencies that occur during XAML reading and XAML writing.</source>
          <target state="translated">针对在 XAML 读取和 XAML 写入过程中出现内部不一致所引发的异常。</target>       </trans-unit>
        <trans-unit id="102" translate="yes" xml:space="preserve" extradata="MT" uid="T:System.Xaml.XamlInternalException">
          <source>This exception is usually thrown only when some aspect of the XAML reader or XAML writer system was extended by your code, and inconsistencies or implementation problems occurred that were passed on to the .NET Framework XAML Services system code.</source>
          <target state="translated">仅在 XAML 读取器或 XAML 编写器系统的某些方面已扩展你的代码，且不一致情况或实现问题发生传递给.NET Framework XAML 服务的系统代码时，就会引发此异常。</target>       </trans-unit>
        <trans-unit id="103" translate="yes" xml:space="preserve" extradata="MT" uid="T:System.Xaml.XamlInternalException">
          <source>Exceptions that might originate from third parties, such as parsing XAML and encountering errors in the XAML, should not throw <ph id="ph1">&lt;xref:System.Xaml.XamlInternalException&gt;</ph>, and should instead throw other exceptions such as <ph id="ph2">&lt;xref:System.Xaml.XamlParseException&gt;</ph> or <ph id="ph3">&lt;xref:System.Xaml.XamlObjectWriterException&gt;</ph>.</source>
          <target state="translated">从第三方，如分析 XAML 和遇到错误在 XAML 中，可能出现的异常不应引发<ph id="ph1">&lt;xref:System.Xaml.XamlInternalException&gt;</ph>，并应改为引发其他异常，如<ph id="ph2">&lt;xref:System.Xaml.XamlParseException&gt;</ph>或<ph id="ph3">&lt;xref:System.Xaml.XamlObjectWriterException&gt;</ph>。</target>       </trans-unit>
        <trans-unit id="104" translate="yes" xml:space="preserve" extradata="MT" uid="T:System.Xaml.XamlInternalException">
          <source>If you are writing code that extends .NET Framework XAML Services, in particular, if you are writing code for a XAML reader or XAML writer implementation, you should maintain this distinction between <ph id="ph1">&lt;xref:System.Xaml.XamlInternalException&gt;</ph> and the other XAML-related exceptions.</source>
          <target state="translated">如果你正在编写扩展.NET Framework XAML 服务的代码，具体而言，如果你正在编写代码的 XAML 读取器或 XAML 编写器实现中，你应维护之间的这一区别<ph id="ph1">&lt;xref:System.Xaml.XamlInternalException&gt;</ph>和其他与 XAML 相关的异常。</target>       </trans-unit>
        <trans-unit id="105" translate="yes" xml:space="preserve" extradata="MT" uid="T:System.Xaml.XamlInternalException">
          <source>Your code should only throw <ph id="ph1">&lt;xref:System.Xaml.XamlInternalException&gt;</ph> in cases where further extension of your class violates some design principle or implementation pattern that your callable code defines.</source>
          <target state="translated">你的代码应只引发<ph id="ph1">&lt;xref:System.Xaml.XamlInternalException&gt;</ph>在其中进一步扩展你的类违反了你可调用的代码定义一些设计原则或实现模式的情况下。</target>       </trans-unit>
        <trans-unit id="106" translate="yes" xml:space="preserve" extradata="MT" uid="T:System.Xaml.XamlInternalException">
          <source>Your code should throw other XAML-specific exceptions for exception cases where your XAML reader or XAML writer implementation is used without extension and is used to load third-party XAML, third-party XAML schema context, and so on.</source>
          <target state="translated">你的代码应引发异常情况下，XAML 读取器或 XAML 编写器实现是不与扩展结合使用，用于加载第三方 XAML、 第三方 XAML 架构上下文，等其他特定于 XAML 的异常。</target>       </trans-unit>
        <trans-unit id="107" translate="yes" xml:space="preserve" uid="T:System.Xaml.XamlInternalException">
          <source>Initializes a new instance of the <ph id="ph1">&lt;see cref="T:System.Xaml.XamlInternalException" /&gt;</ph> class.</source>
          <target state="translated">初始化 <ph id="ph1">&lt;see cref="T:System.Xaml.XamlInternalException" /&gt;</ph> 类的新实例。</target>       </trans-unit>
        <trans-unit id="108" translate="yes" xml:space="preserve" uid="M:System.Xaml.XamlInternalException.#ctor">
          <source>Initializes a new instance of the <ph id="ph1">&lt;see cref="T:System.Xaml.XamlInternalException" /&gt;</ph> class with a system-supplied message that describes the error.</source>
          <target state="translated">使用由系统提供的用于描述错误的消息初始化 <ph id="ph1">&lt;see cref="T:System.Xaml.XamlInternalException" /&gt;</ph> 类的新实例。</target>       </trans-unit>
        <trans-unit id="109" translate="yes" xml:space="preserve" uid="M:System.Xaml.XamlInternalException.#ctor(System.String)">
          <source>The message that describes the exception.</source>
          <target state="translated">描述该异常的消息。</target>       </trans-unit>
        <trans-unit id="110" translate="yes" xml:space="preserve" uid="M:System.Xaml.XamlInternalException.#ctor(System.String)">
          <source>Initializes a new instance of the <ph id="ph1">&lt;see cref="T:System.Xaml.XamlInternalException" /&gt;</ph> class with a specified message that describes the error.</source>
          <target state="translated">使用指定的描述错误的消息初始化 <ph id="ph1">&lt;see cref="T:System.Xaml.XamlInternalException" /&gt;</ph> 类的新实例。</target>       </trans-unit>
        <trans-unit id="111" translate="yes" xml:space="preserve" uid="M:System.Xaml.XamlInternalException.#ctor(System.Runtime.Serialization.SerializationInfo,System.Runtime.Serialization.StreamingContext)">
          <source>The object that holds the serialized object data.</source>
          <target state="translated">承载序列化对象数据的对象。</target>       </trans-unit>
        <trans-unit id="112" translate="yes" xml:space="preserve" uid="M:System.Xaml.XamlInternalException.#ctor(System.Runtime.Serialization.SerializationInfo,System.Runtime.Serialization.StreamingContext)">
          <source>The contextual information about the source or destination.</source>
          <target state="translated">关于来源和目标的上下文信息</target>       </trans-unit>
        <trans-unit id="113" translate="yes" xml:space="preserve" uid="M:System.Xaml.XamlInternalException.#ctor(System.Runtime.Serialization.SerializationInfo,System.Runtime.Serialization.StreamingContext)">
          <source>Initializes a new instance of the <ph id="ph1">&lt;see cref="T:System.Xaml.XamlInternalException" /&gt;</ph> class with serialized data.</source>
          <target state="translated">用序列化数据初始化 <ph id="ph1">&lt;see cref="T:System.Xaml.XamlInternalException" /&gt;</ph> 类的新实例。</target>       </trans-unit>
        <trans-unit id="114" translate="yes" xml:space="preserve" uid="M:System.Xaml.XamlInternalException.#ctor(System.String,System.Exception)">
          <source>The message that describes the exception.</source>
          <target state="translated">描述该异常的消息。</target>       </trans-unit>
        <trans-unit id="115" translate="yes" xml:space="preserve" uid="M:System.Xaml.XamlInternalException.#ctor(System.String,System.Exception)">
          <source>The exception that is the cause of the current exception.</source>
          <target state="translated">导致当前异常的异常。</target>       </trans-unit>
        <trans-unit id="116" translate="yes" xml:space="preserve" uid="M:System.Xaml.XamlInternalException.#ctor(System.String,System.Exception)">
          <source>If the <bpt id="p1">&lt;c&gt;</bpt>innerException<ept id="p1">&lt;/c&gt;</ept> parameter is not <ph id="ph1">&lt;see langword="null" /&gt;</ph>, the current exception is raised in a <ph id="ph2">&lt;see langword="catch" /&gt;</ph> block that handles the inner exception.</source>
          <target state="translated">如果 <bpt id="p1">&lt;c&gt;</bpt>innerException<ept id="p1">&lt;/c&gt;</ept> 参数不为 <ph id="ph1">&lt;see langword="null" /&gt;</ph>，则当前异常会在处理内部异常的 <ph id="ph2">&lt;see langword="catch" /&gt;</ph> 块中引发。</target>       </trans-unit>
        <trans-unit id="117" translate="yes" xml:space="preserve" uid="M:System.Xaml.XamlInternalException.#ctor(System.String,System.Exception)">
          <source>Initializes a new instance of the <ph id="ph1">&lt;see cref="T:System.Xaml.XamlInternalException" /&gt;</ph> class with a specified error message and a reference to the inner exception that is the cause of this exception.</source>
          <target state="translated">使用指定的错误消息和对作为此异常原因的内部异常的引用来初始化 <ph id="ph1">&lt;see cref="T:System.Xaml.XamlInternalException" /&gt;</ph> 类的新实例。</target>       </trans-unit>
      </group>
    </body>
  </file>
</xliff>